USE [master]
GO
/****** Object:  Database [dbmembers]    Script Date: 07/12/2022 19:23:34 ******/
CREATE DATABASE [dbmembers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbmembers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbmembers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbmembers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbmembers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbmembers] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbmembers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbmembers] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbmembers] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbmembers] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbmembers] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbmembers] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbmembers] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbmembers] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbmembers] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbmembers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbmembers] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbmembers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbmembers] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbmembers] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbmembers] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbmembers] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dbmembers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbmembers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbmembers] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbmembers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbmembers] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbmembers] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbmembers] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbmembers] SET RECOVERY FULL 
GO
ALTER DATABASE [dbmembers] SET  MULTI_USER 
GO
ALTER DATABASE [dbmembers] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbmembers] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dbmembers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dbmembers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dbmembers] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dbmembers] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbmembers', N'ON'
GO
ALTER DATABASE [dbmembers] SET QUERY_STORE = OFF
GO
USE [dbmembers]
GO
/****** Object:  Table [dbo].[ROLE_INFO]    Script Date: 07/12/2022 19:23:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE_INFO](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_NAME] [nvarchar](100) NULL,
 CONSTRAINT [PK_ROLE_INFO] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_INFO]    Script Date: 07/12/2022 19:23:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_INFO](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_FIRSTNAME] [nvarchar](150) NULL,
	[USER_LASTNAME] [nvarchar](150) NULL,
	[USER_EMAIL] [nvarchar](max) NULL,
	[USER_PASSWORD] [nvarchar](max) NULL,
	[USER_DELETE_FLAG] [bit] NOT NULL,
	[USER_CREATEDATETIME] [datetime] NULL,
	[USER_MIDIFYDATETIME] [datetime] NULL,
	[USER_DATEOFBIRTH] [int] NULL,
	[ROLE_ID] [int] NULL,
 CONSTRAINT [PK_USER_INFO] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ROLE_INFO] ON 
GO
INSERT [dbo].[ROLE_INFO] ([ROLE_ID], [ROLE_NAME]) VALUES (1, N'Admin')
GO
INSERT [dbo].[ROLE_INFO] ([ROLE_ID], [ROLE_NAME]) VALUES (2, N'Employee')
GO
INSERT [dbo].[ROLE_INFO] ([ROLE_ID], [ROLE_NAME]) VALUES (3, N'Member')
GO
SET IDENTITY_INSERT [dbo].[ROLE_INFO] OFF
GO
SET IDENTITY_INSERT [dbo].[USER_INFO] ON 
GO
INSERT [dbo].[USER_INFO] ([USER_ID], [USER_FIRSTNAME], [USER_LASTNAME], [USER_EMAIL], [USER_PASSWORD], [USER_DELETE_FLAG], [USER_CREATEDATETIME], [USER_MIDIFYDATETIME], [USER_DATEOFBIRTH], [ROLE_ID]) VALUES (1, N'คุณิตา', N'บุญยอง', N'kunita.boonyong@gmail.com', N'mhtg6XNHc4s0y9MLjsoFLA==.RLnJJhWel/3GJ1LxsqDv/2dGK2fezgVpjLYhOEmgPRI=', 0, CAST(N'2022-12-07T17:23:25.957' AS DateTime), CAST(N'2022-12-07T17:23:25.957' AS DateTime), NULL, 3)
GO
SET IDENTITY_INSERT [dbo].[USER_INFO] OFF
GO
ALTER TABLE [dbo].[USER_INFO] ADD  CONSTRAINT [DF_USER_INFO_USER_DELETE_FLAG]  DEFAULT ((0)) FOR [USER_DELETE_FLAG]
GO
/****** Object:  StoredProcedure [dbo].[uspGetUserByEmail]    Script Date: 07/12/2022 19:23:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Kunita
-- Create date: 07/12/2022
-- Description:	get user by  email
-- =============================================
CREATE PROCEDURE [dbo].[uspGetUserByEmail] 
	-- Add the parameters for the stored procedure here
	@USER_EMAIL NVARCHAR(MAX)
AS
BEGIN
	SELECT *
	FROM [dbo].[USER_INFO] U JOIN [dbo].[ROLE_INFO] R
		 ON U.ROLE_ID = R.ROLE_ID
	WHERE U.USER_EMAIL = @USER_EMAIL
END
GO
/****** Object:  StoredProcedure [dbo].[uspRegisterMember]    Script Date: 07/12/2022 19:23:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Kunita
-- Create date: 07/12/2022
-- Description:	Register user
-- =============================================
CREATE PROCEDURE [dbo].[uspRegisterMember]
	-- Add the parameters for the stored procedure here
	@USER_FIRSTNAME nvarchar(150),
	@USER_LASTNAME nvarchar(150),
	@USER_PASSWORD nvarchar(max),
	@USER_EMAIL nvarchar(max)
AS
BEGIN

	INSERT INTO [dbo].[USER_INFO]
           ([USER_FIRSTNAME]
           ,[USER_LASTNAME]
		   ,[USER_EMAIL]
           ,[USER_PASSWORD]
           ,[ROLE_ID]
		   ,[USER_CREATEDATETIME]
		   ,[USER_MIDIFYDATETIME])
     VALUES
           (@USER_FIRSTNAME
           ,@USER_LASTNAME
		   ,@USER_EMAIL
           ,@USER_PASSWORD
           ,3
		   ,GETDATE()
		   ,GETDATE())
END
GO
USE [master]
GO
ALTER DATABASE [dbmembers] SET  READ_WRITE 
GO
